---
name: "NapiSub"
guid: "6F9A84BF-CB2F-42C3-9F07-4037956F9A02"
version: "1.0.0.0"
targetAbi: "10.7.0.0"
framework: "net5.0"
overview: "Subtitles downloader"
description: >
 Download subtitles for Movies and TV Shows using napiprojekt.pl database.
category: "General"
owner: "jellyfin"
artifacts:
- "Jellyfin.Plugin.NapiSub.dll"
changelog: >
  changelog
